import Head from 'next/head'
import Header from './header'

export default function Layout(props) {

    const { title, children } = props

    return (
        <>
            <Head>
              <title>{ title }</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header/>

            { children }
            
        </>
    )
}
