import { useRouter } from 'next/router'
import Head from 'next/head'

import Layout from '../../components/layout'

export default function TvDetail({ tvDetailData }) {

    const router = useRouter()

    if (router.isFallback) {
        return (
            <>
                <Head>
                  <title>Watchlist</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                
                <div className="flex h-screen w-full items-center justify-center">
                    <h1 className="text-7xl font-medium text-center text-red-700 animate-bounce">W</h1>                
                </div>
            </>
        )
    }

    return (
        <Layout title={`${tvDetailData.name} | Watchlist`}>
            <main>
                <div className="w-full h-full sm:h-96 lg:h-120 xl:h-140">                
                    <img 
                        className="w-full sm:w-96 lg:w-128 xl:w-180 h-full sm:h-96 lg:h-120 xl:h-140 sm:object-center sm:object-cover sm:z-0 bg-gradient-to-t from-red-500"
                        src={`https://image.tmdb.org/t/p/original/${tvDetailData.backdrop_path}`} 
                        alt="Backdrop" 
                        align="right"
                    />            
                    <div className="flex flex-col w-full content-center justify-start px-3 sm:px-5 xl:px-8 sm:z-10 sm:absolute h-full sm:h-96 lg:h-120 xl:h-140 sm:bg-gradient-to-r sm:from-black sm:via-black">
                        <div className="my-auto xl:pb-20 sm:w-1/2">
                            <h1 className="text-3xl sm:text-4xl lg:text-5xl mb-4 mt-4 sm:mt-0 font-medium">{tvDetailData.name}</h1>
                            <p className="sm:text-sm lg:text-base mb-4 text-justify font-light font-description">{tvDetailData.overview}</p>
                            <p 
                                className="sm:text-sm lg:text-base mb-4 font-light font-description"
                            >
                                {tvDetailData.first_air_date.substring(0,4)} | {tvDetailData.number_of_seasons >= 2 ? `${tvDetailData.number_of_seasons} Seasons` : `${tvDetailData.number_of_seasons} Season` } | &nbsp;
                                {tvDetailData.genres.map( (items, index) => {
                                    if (index === tvDetailData.genres.length -1) {
                                        return items.name    
                                    }
                                    return items.name+", "
                                })}
                            </p>
                        </div>
                    </div>
                </div>
            </main>
        </Layout>
    )
}

export const getStaticPaths = async () => {
    const tvTrendingRes = await fetch(`https://api.themoviedb.org/3/trending/tv/day?api_key=${process.env.API_KEY}`)
    const tvTrending = await tvTrendingRes.json()

    const tvPopularRes = await fetch(`https://api.themoviedb.org/3/tv/popular?api_key=${process.env.API_KEY}&language=en-US&page=1`)
    const tvPopular = await tvPopularRes.json()

    const tvAiringRes = await fetch(`https://api.themoviedb.org/3/tv/on_the_air?api_key=${process.env.API_KEY}&language=en-US&page=1`)
    const tvAiring = await tvAiringRes.json()
     
    const actionDataRes = await fetch(`https://api.themoviedb.org/3/discover/tv?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_genres=10759&include_null_first_air_dates=false&with_watch_monetization_types=flatrate`)
    const actionData = await actionDataRes.json()

    const comedyDataRes = await fetch(`https://api.themoviedb.org/3/discover/tv?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_genres=35&include_null_first_air_dates=false&with_watch_monetization_types=flatrate`)
    const comedyData = await comedyDataRes.json()

    const dramaDataRes = await fetch(`https://api.themoviedb.org/3/discover/tv?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_genres=18&include_null_first_air_dates=false&with_watch_monetization_types=flatrate`)
    const dramaData = await dramaDataRes.json()

    const animationDataRes = await fetch(`https://api.themoviedb.org/3/discover/tv?api_key=${process.env.API_KEY}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_genres=16&include_null_first_air_dates=false&with_watch_monetization_types=flatrate`)
    const animationData = await animationDataRes.json()

    const data = [
        ...tvTrending.results,
        ...tvPopular.results,
        ...tvAiring.results,
        ...actionData.results,
        ...comedyData.results,
        ...dramaData.results,
        ...animationData.results
    ]

    const paths = data.map( items => {
        return {
            params: {
                id: items.id.toString()
            }
        }
    })

    return {
        paths,
        fallback: true
    }
}

export const getStaticProps = async (paths) => {
    const id = paths.params.id
    const res = await fetch(`https://api.themoviedb.org/3/tv/${id}?api_key=${process.env.API_KEY}&language=en-US`)
    const data = await res.json()

    return {
        props: {
            tvDetailData: data
        },
        revalidate: 1
    }
}
